AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM file for game-pop-poller process
Resources:
  gamepoppoller:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 180
      Role: 'arn:aws:iam::614634389718:role/lambda_basic_execution'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
